# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Form")
        Dialog.resize(1191, 800)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("background-color:#2c313c;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QVideoWidget(self.frame)
        self.widget_2.setMinimumSize(QtCore.QSize(1000, 575))
        self.widget_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout.addWidget(self.widget_2)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OpenButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpenButton.sizePolicy().hasHeightForWidth())
        self.OpenButton.setSizePolicy(sizePolicy)
        self.OpenButton.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.OpenButton.setFont(font)
        self.OpenButton.setStyleSheet("QPushButton {    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35,35, 35);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {        \n"
"    background-color: rgb(55, 55, 55);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}\n"
"\n"
"")
        self.OpenButton.setObjectName("OpenButton")
        self.horizontalLayout_2.addWidget(self.OpenButton)
        self.PlayButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlayButton.sizePolicy().hasHeightForWidth())
        self.PlayButton.setSizePolicy(sizePolicy)
        self.PlayButton.setMinimumSize(QtCore.QSize(0, 25))
        self.PlayButton.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(35,35, 35);\n"
"    border-radius:10px;\n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPushButton:hover {    \n"
"  background-color:rgb(55,55,55)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(255, 0, 0);    \n"
"    color: rgb(35, 35, 35);\n"
"}\n"
"\n"
"")
        self.PlayButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../individual-project/images/play (2).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PlayButton.setIcon(icon)
        self.PlayButton.setIconSize(QtCore.QSize(20, 16))
        self.PlayButton.setObjectName("PlayButton")
        self.horizontalLayout_2.addWidget(self.PlayButton)
        self.VideoSlider = QtWidgets.QSlider(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VideoSlider.sizePolicy().hasHeightForWidth())
        self.VideoSlider.setSizePolicy(sizePolicy)
        self.VideoSlider.setMinimumSize(QtCore.QSize(0, 25))
        self.VideoSlider.setMaximumSize(QtCore.QSize(1521512, 16777215))
        self.VideoSlider.setStyleSheet("QSlider {    \n"
"    background-color: rgb(35,35, 35);;\n"
"    border-radius: 10px;\n"
"    color: rgb(139, 0, 0);\n"
"}\n"
"QSlider:hover {    \n"
"    \n"
"    background-color: rgb(55, 55, 55);\n"
"}")
        self.VideoSlider.setMaximum(100)
        self.VideoSlider.setProperty("value", 0)
        self.VideoSlider.setSliderPosition(0)
        self.VideoSlider.setOrientation(QtCore.Qt.Horizontal)
        self.VideoSlider.setObjectName("VideoSlider")
        self.horizontalLayout_2.addWidget(self.VideoSlider)
        self.VolumeSlider = QtWidgets.QSlider(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VolumeSlider.sizePolicy().hasHeightForWidth())
        self.VolumeSlider.setSizePolicy(sizePolicy)
        self.VolumeSlider.setMinimumSize(QtCore.QSize(0, 25))
        self.VolumeSlider.setStyleSheet("QSlider:hover {    \n"
"   background-color: rgb(55, 55, 55);\n"
"}\n"
"QSlider {    \n"
"    background-color: rgb(35,35, 35);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 0, 0);;\n"
"}\n"
"\n"
"")
        self.VolumeSlider.setMaximum(100)
        self.VolumeSlider.setProperty("value", 50)
        self.VolumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.VolumeSlider.setObjectName("VolumeSlider")
        self.horizontalLayout_2.addWidget(self.VolumeSlider)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setMinimumSize(QtCore.QSize(10, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButton.setStyleSheet("QPushButton {    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35,35, 35);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {        \n"
"    background-color: rgb(55, 55, 55);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../individual-project/images/maximize.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_2.setStyleSheet("QPushButton {    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35,35, 35);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {        \n"
"    background-color: rgb(55, 55, 55);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Form", "Form"))
        self.OpenButton.setText(_translate("Form", "Открыть"))
        self.pushButton_2.setText(_translate("Form", "Вернуться в меню"))
    # def event_filter(self,source,event):
    #     if qApp.activePopupWidget() is None:
    #         if event.type() == QEvent.MouseMove:
    #             if self.frame_2.isHidden():
    #                 rect = self.geometry()
    #                 rect.setHeight(46)
    #                 if rect.contains(event.globalPos()):
    #                    self.frame_2.show()
    #             else:
    #                 rect = QRect(
    #                     self.frame_2.mapToGlobal(QPoint(0,0)),
    #                     self.frame_2.size())
    #                 if not rect.contains(event.globalPos()):
    #                     self.frame_2.hide()
    #         elif event.type() == QEvent.Leave and source is self:
    #             self.frame_2.hide()
    #     return super().eventFilter(source,event)
from PyQt5.QtMultimediaWidgets import QVideoWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Form()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
